/**
 * Bakes the 3D icon PNGs into inline data URIs (lib/icon3d.generated.ts).
 *
 * The icons render at 20-24px but ship as 256x256 PNGs (24-42KB each). Served as
 * separate <img> requests they land after first paint, so they visibly pop in.
 * Downscaling to 96px (4x the largest render size, so still crisp on retina) and
 * inlining them as WebP data URIs drops them to a few KB each and lets them paint
 * with the server-rendered HTML — zero network requests, zero pop-in.
 *
 * Re-run after adding or changing an icon in public/icons/3d/:
 *   node scripts/build-icon3d.mjs
 */
import { readdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import sharp from "sharp";

const SRC_DIR = path.join(process.cwd(), "public", "icons", "3d");
const OUT_FILE = path.join(process.cwd(), "lib", "icon3d.generated.ts");
const SIZE = 96;

const files = (await readdir(SRC_DIR)).filter((f) => f.endsWith(".png")).sort();

const entries = [];
for (const file of files) {
  const name = path.basename(file, ".png");
  const input = await readFile(path.join(SRC_DIR, file));
  const webp = await sharp(input)
    .resize(SIZE, SIZE, { fit: "contain", background: { r: 0, g: 0, b: 0, alpha: 0 } })
    .webp({ quality: 90, effort: 6 })
    .toBuffer();

  entries.push({ name, uri: `data:image/webp;base64,${webp.toString("base64")}` });
  const before = (input.length / 1024).toFixed(1);
  const after = (webp.length / 1024).toFixed(1);
  console.log(`${name.padEnd(12)} ${before.padStart(6)}KB -> ${after.padStart(5)}KB`);
}

const body = `// GENERATED by scripts/build-icon3d.mjs — do not edit by hand.
// Source: public/icons/3d/*.png, downscaled to ${SIZE}px and inlined as WebP.

export type Icon3DName =
${entries.map((e) => `  | "${e.name}"`).join("\n")};

export const ICON_3D: Record<Icon3DName, string> = {
${entries.map((e) => `  ${e.name}: "${e.uri}",`).join("\n")}
};
`;

await writeFile(OUT_FILE, body, "utf8");

const total = entries.reduce((n, e) => n + e.uri.length, 0);
console.log(`\nWrote ${entries.length} icons to lib/icon3d.generated.ts (~${(total / 1024).toFixed(1)}KB inlined)`);
